import "~/styles/globals.css";
import '@coinbase/onchainkit/styles.css';
import '@rainbow-me/rainbowkit/styles.css';

import { type Metadata } from "next";
import { twMerge } from "tailwind-merge";
import { accentFont, baseFont } from "~/font";
import dynamic from "next/dynamic";
import SideMenu from "~/components/SideMenu";

export const metadata: Metadata = {
  title: "BasedCoffee",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


const Providers = dynamic(
  () => import('src/components/WalletProvider'),
  {
    ssr: false,
  },
);

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={twMerge(baseFont.variable, accentFont.variable)}>
      <body>
        <Providers>
          {children}
          <SideMenu />
        </Providers>
      </body>
    </html>
  );
}
